# ui.R

library(shiny)

shinyUI(fluidPage(
        titlePanel("Historical Volatility Analysis on SP500 Daily Prices"),
        sidebarLayout(
                sidebarPanel(
                        br(),
                        br(),
                        br(),
                        helpText("Note:"),
                        br(),
                        helpText("This Shiny App use data of the closing daily price from finance.yahoo.com."),
                        helpText("Data should be available for at least the previous business day.",
                                 "Calculations are possible for EWMA, whenever there are two or more",
                                 "business days in the index date range."),
                        helpText("Calculations are possible for 1-M MA, whenever there are 21 or more",
                                 "business days in the index date range."),
                        helpText("Calculations are possible for 3-M MA, whenever there are 63 or more",
                                 "business days in the index date range."),
                        helpText("Calculations are possible for 6-M MA, whenever there are 126 or more",
                                 "business days in the index date range."),
                        br(),
                        br(),
                        br(),
                        dateRangeInput(
                                "dateRng", 
                                "Index Date Range", 
                                start = as.Date("2013-10-15"), 
                                end = NULL, 
                                min = NULL, 
                                max = NULL, 
                                format = "yyyy-mm-dd", 
                                startview = "month", 
                                weekstart = 1, 
                                language = "en", 
                                separator = " to"),
                        checkboxGroupInput("volcalc", 
                                           label = h4("Volatility Calculations in Graph"), 
                                           choices = list(
                                                   "Exponential Moving Average" = 1,
                                                   "1-month Moving Average" = 2,
                                                   "3-month Moving Average" = 3,
                                                   "6-month Moving Average" = 4), 
                                           selected = NULL),
                        submitButton("Update")
                ),
                
                mainPanel(
                        p("Volatility is a measure of variability in prices or price indexes.",
                           "This Shiny apps uses up to 4 methods to estimate volatility."),
                        p("For exemplification on volatility behaviour across time, close price data of the ",
                          "SP500 index is used and dates can be selected in the left side panel."),
                        h3("Daily variation"),
                        p("Price daily variation can be measured in different ways.  From the plot above, ",
                          "it can be seen that prices fluctuate daily and form a jigsaw line that fluctuates ",
                          "around some tendency."),
                        p("This fluctuation is called daily variation."),
                        plotOutput("pricePlot"),
                        h3("Logarithmic Return as Measure of Daily Variation"),
                        p("Daily variation is measured in different ways.  There is the simple",
                          "difference between today and yesterdays' prices, the daily percentage variation (simple return), ",
                          "the total daily return, the logarithmic daily return, etc."),
                        p("The logarithmic return, defined as the natural logarithm of the today and yesterdays' ",
                          "price ratio, is a measure that theoretically have a normal distribution,",
                          "which makes it suitable to be used in several financial models.",
                          "A histogram and a density plot of the logarithmic returns (or logreturns)",
                          "is shown below and it looks like a normal distribution."),
                        p("The volatility of the prices is defined as the standard deviation of the",
                          "normal distribution of the logreturns."),
                        plotOutput("distPlot"),
                        h3("Volatility Estimation"),
                        p("From the graph below, the logreturns seem to vary low in some",
                          "periods of time, and high in some others.  This changes in ",
                          "variability account for changes in the risk perception from",
                          "investors, which vary over time."),
                        p("There are many ways of estimating volatility.  In this project",
                          "two ways are shown using smoothing."),
                        p("In the checkbox, there are two kinds of options, the exponential weighted",
                          "moving average and the moving average."),
                        p("This moving averages are not averages per se but proxys of the standard deviation."),
                        plotOutput("volPlot"),
                        h4("Exponential Moving Average (EWMA)"),
                        p("Check the first option in the checkbox above to see the EWMA",
                          "results.  This EWMA estimation is the square root of the exponential smoothing of ",
                          "the squared logreturns."),
                        p("The result is a volatility estimation that is very reactive to ",
                          "recent data, since the weights are higher for recent prices."),
                        h4("Moving Averages"),
                        p("Check any of the other 3 options in the checkbox above to see the moving average",
                          "results.  The moving average volatility estimation is the square root of the ",
                          "average of square roots in a moving window of data."),
                        p("This estimation is highly reactive for a window with few data (like the 1 month) and",
                          "with more data, the estimation is smoother.  Nevertheless, the data is weighted uniformly, ",
                          "in contrast with EWMA, which weighs higher recent data and applies a weight to every logreturn."),
                        p("Compare the behaviour of the EWMA estimation versus each one of the moving average ones."),
                        br(),
                        br()
                )
        )
))
